#!/usr/bin/env snakemake

"""
______             ___                         _     _
| ___ \           / _ \                       | |   | |
| |_/ / __ _  ___/ /_\ \___ ___  ___ _ __ ___ | |__ | |_   _
| ___ \/ _` |/ __|  _  / __/ __|/ _ \ '_ ` _ \| '_ \| | | | |
| |_/ / (_| | (__| | | \__ \__ \  __/ | | | | | |_) | | |_| |
\____/ \__,_|\___\_| |_/___/___/\___|_| |_| |_|_.__/|_|\__, |
                                                        __/ |
                                                       |___/

           Omics for All, Open Source for All

    Hybrid assembly and polish using short and long reads

"""

import sys
import pandas as pd
import bacassembly

shell.executable("bash")

SAMPLES = bacassembly.parse_samples(config)

include: "rules/raw.smk"
include: "rules/trimming.smk"


rule all:
    input:
        rules.trimming_all.input
